# This file contains values from Cookiecutter

default_context:
  project_name: "mapraster"
  project_description: "mapraster is a Python lib to interpolate xarray raster field on image geometry (e.g. line/sample)"
  organization: "umr-lops"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "agrouaze"
  email: "antoine.grouazel@ifremer.fr"
  version: "2025.12.18"
  line_length: "88"
  create_example_template: "none"
